# Use root/example user/password credentials
version: '3.1'

services:
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public_html/:/var/www/html/

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: test
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: wingsdb
    volumes:
      - ./wingsxi/sql-wings/:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    name: nginx-network
    external: true
