<?php
    // BCNM 20
        $bcnms_master_table['creeping_doom'] = array(
            array(
                array( "itemid" =>   816, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 65535, "droprate" => 1000, "amount" => 3000),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  700),
                array( "itemid" =>   816, "droprate" =>  300),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  900),
                array( "itemid" =>   816, "droprate" =>  100),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  300),
                array( "itemid" => 14733, "droprate" =>   40),
                array( "itemid" => 14735, "droprate" =>   50),
                array( "itemid" => 14738, "droprate" =>   50),
                array( "itemid" => 13439, "droprate" =>   50),
                array( "itemid" => 13437, "droprate" =>   40),
                array( "itemid" => 14730, "droprate" =>   45),
                array( "itemid" => 13438, "droprate" =>   50),
                array( "itemid" => 14737, "droprate" =>   40),
                array( "itemid" => 13435, "droprate" =>   50),
                array( "itemid" => 14731, "droprate" =>   45),
                array( "itemid" => 13436, "droprate" =>   45),
                array( "itemid" => 14736, "droprate" =>   50),
                array( "itemid" => 14734, "droprate" =>   50),
                array( "itemid" => 14729, "droprate" =>   45),
                array( "itemid" => 14732, "droprate" =>   50),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  700),
                array( "itemid" => 14733, "droprate" =>   20),
                array( "itemid" => 14735, "droprate" =>   20),
                array( "itemid" => 14738, "droprate" =>   20),
                array( "itemid" => 13439, "droprate" =>   20),
                array( "itemid" => 13437, "droprate" =>   20),
                array( "itemid" => 14730, "droprate" =>   20),
                array( "itemid" => 13438, "droprate" =>   20),
                array( "itemid" => 14737, "droprate" =>   20),
                array( "itemid" => 13435, "droprate" =>   20),
                array( "itemid" => 14731, "droprate" =>   20),
                array( "itemid" => 13436, "droprate" =>   20),
                array( "itemid" => 14736, "droprate" =>   20),
                array( "itemid" => 14734, "droprate" =>   20),
                array( "itemid" => 14729, "droprate" =>   20),
                array( "itemid" => 14732, "droprate" =>   20),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  500),
                array( "itemid" =>  1134, "droprate" =>  400),
                array( "itemid" =>  4116, "droprate" =>  100),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  500),
                array( "itemid" =>   694, "droprate" =>  250),
                array( "itemid" =>  4132, "droprate" =>  250),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  250),
                array( "itemid" =>  4751, "droprate" =>  150),
                array( "itemid" =>  4868, "droprate" =>  200),
                array( "itemid" =>  5070, "droprate" =>  250),
                array( "itemid" =>  4947, "droprate" =>  150),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  300),
                array( "itemid" =>   814, "droprate" =>   50),
                array( "itemid" =>   645, "droprate" =>   50),
                array( "itemid" =>   690, "droprate" =>   50),
                array( "itemid" =>   651, "droprate" =>   50),
                array( "itemid" =>   643, "droprate" =>   50),
                array( "itemid" =>   795, "droprate" =>   50),
                array( "itemid" =>   653, "droprate" =>   50),
                array( "itemid" =>   644, "droprate" =>   50),
                array( "itemid" =>   799, "droprate" =>   50),
                array( "itemid" =>   807, "droprate" =>   50),
                array( "itemid" =>   744, "droprate" =>   50),
                array( "itemid" =>   736, "droprate" =>   50),
                array( "itemid" =>   652, "droprate" =>   50),
                array( "itemid" =>   806, "droprate" =>   50),
                array( "itemid" =>   796, "droprate" =>   50),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  500),
                array( "itemid" =>   814, "droprate" =>   30),
                array( "itemid" =>   645, "droprate" =>   40),
                array( "itemid" =>   690, "droprate" =>   30),
                array( "itemid" =>   651, "droprate" =>   30),
                array( "itemid" =>   643, "droprate" =>   40),
                array( "itemid" =>   795, "droprate" =>   30),
                array( "itemid" =>   653, "droprate" =>   40),
                array( "itemid" =>   644, "droprate" =>   40),
                array( "itemid" =>   799, "droprate" =>   30),
                array( "itemid" =>   807, "droprate" =>   30),
                array( "itemid" =>   744, "droprate" =>   40),
                array( "itemid" =>   736, "droprate" =>   30),
                array( "itemid" =>   652, "droprate" =>   30),
                array( "itemid" =>   806, "droprate" =>   30),
                array( "itemid" =>   796, "droprate" =>   30),
            ),
        );   
    // BCNM 30
        $bcnms_master_table['petrifying pair'] = array(
            array(
                array( "itemid" => 852, "droprate" => 1000 ), 
            ),      
            array(
                array( "itemid" => 15282, "droprate" =>   50 ), 
                array( "itemid" => 15275, "droprate" =>   75 ), 
                array( "itemid" => 15278, "droprate" =>  175 ), 
                array( "itemid" =>   694, "droprate" =>  175 ), 
                array( "itemid" =>   690, "droprate" =>  350 ), 
                array( "itemid" =>   652, "droprate" =>  100 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  925 ), 
                array( "itemid" => 15282, "droprate" =>   50 ), 
                array( "itemid" => 15275, "droprate" =>   75 ), 
                array( "itemid" => 15278, "droprate" =>  175 ), 
                array( "itemid" =>   694, "droprate" =>  175 ), 
                array( "itemid" =>   690, "droprate" =>  350 ), 
                array( "itemid" =>   652, "droprate" =>  100 ), 
            ),
            array(
                array( "itemid" => 15285, "droprate" => 105 ),
                array( "itemid" => 15279, "droprate" => 105 ),
                array( "itemid" => 651, "droprate" => 131 ),  
                array( "itemid" => 643, "droprate" => 131 ),  
                array( "itemid" => 644, "droprate" => 79 ),   
                array( "itemid" => 736, "droprate" => 79 ),   
                array( "itemid" => 795, "droprate" => 131 ),  
            ),
            array(
                array( "itemid" => 17867, "droprate" => 552 ),
                array( "itemid" => 4877, "droprate" => 263 ), 
                array( "itemid" => 4878, "droprate" => 210 ), 
                array( "itemid" => 4876, "droprate" => 289 ), 
                array( "itemid" => 4868, "droprate" => 105 ), 
                array( "itemid" => 4751, "droprate" => 79 ),  
                array( "itemid" => 5070, "droprate" => 421 ), 
                array( "itemid" => 4947, "droprate" => 79 ),  
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  736 ), 
                array( "itemid" => 15271, "droprate" =>  200 ), 
                array( "itemid" => 15272, "droprate" =>  125 ), 
                array( "itemid" =>   809, "droprate" =>   10 ), 
                array( "itemid" => 15276, "droprate" =>   75 ), 
                array( "itemid" =>   645, "droprate" =>  100 ), 
                array( "itemid" => 15281, "droprate" =>   25 ), 
                array( "itemid" =>  4132, "droprate" =>  175 ), 
                array( "itemid" => 15284, "droprate" =>  200 ), 
                array( "itemid" =>   796, "droprate" =>   75 ), 
                array( "itemid" => 15273, "droprate" =>  175 ), 
                array( "itemid" =>   653, "droprate" =>  200 ), 
                array( "itemid" =>   799, "droprate" =>   25 ), 
                array( "itemid" => 15283, "droprate" =>  250 ), 
                array( "itemid" => 15277, "droprate" =>  100 ), 
                array( "itemid" => 15280, "droprate" =>  100 ), 
                array( "itemid" => 15274, "droprate" =>  150 ), 
                array( "itemid" =>   744, "droprate" =>  100 ), 
                array( "itemid" =>   806, "droprate" =>  125 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" => 2210 ), 
                array( "itemid" => 15271, "droprate" =>  200 ), 
                array( "itemid" => 15272, "droprate" =>  125 ), 
                array( "itemid" =>   809, "droprate" =>   10 ), 
                array( "itemid" => 15276, "droprate" =>   75 ), 
                array( "itemid" =>   645, "droprate" =>  100 ), 
                array( "itemid" => 15281, "droprate" =>   25 ), 
                array( "itemid" =>  4132, "droprate" =>  175 ), 
                array( "itemid" => 15284, "droprate" =>  200 ), 
                array( "itemid" =>   796, "droprate" =>   75 ), 
                array( "itemid" => 15273, "droprate" =>  175 ), 
                array( "itemid" =>   653, "droprate" =>  200 ), 
                array( "itemid" =>   799, "droprate" =>   25 ), 
                array( "itemid" => 15283, "droprate" =>  250 ), 
                array( "itemid" => 15277, "droprate" =>  100 ), 
                array( "itemid" => 15280, "droprate" =>  100 ), 
                array( "itemid" => 15274, "droprate" =>  150 ), 
                array( "itemid" =>   744, "droprate" =>  100 ), 
                array( "itemid" =>   806, "droprate" =>  125 ), 
            ),
        );
    // BCNM 40
        $bcnms_master_table['royal_jelly'] = array(
            array(
                array( "itemid" => 637, "droprate" => 1000 ),
            ),
            array(
                array( "itemid" => 637, "droprate" => 1000 ),
            ),
            array(
                array( "itemid" => 14651, "droprate" => 450 ),
                array( "itemid" => 17693, "droprate" => 150 ),
                array( "itemid" => 17936, "droprate" => 100 ),
                array( "itemid" => 17696, "droprate" => 100 ),
                array( "itemid" => 4947, "droprate" => 100 ),
            ),
            array(
                array( "itemid" => 14650, "droprate" => 250 ),
                array( "itemid" => 17573, "droprate" => 100 ),
                array( "itemid" => 17463, "droprate" => 100 ),
                array( "itemid" => 17203, "droprate" => 100 ),
                array( "itemid" => 17572, "droprate" => 150 ),
            ),
            array(
                array( "itemid" => 652, "droprate" => 200 ),
                array( "itemid" => 4874, "droprate" => 150 ),
                array( "itemid" => 4751, "droprate" => 150 ),
                array( "itemid" => 4714, "droprate" => 150 ),
                array( "itemid" => 4896, "droprate" => 150 ),
                array( "itemid" => 666, "droprate" => 200 ),
            ),
            array(
                array( "itemid" => 770, "droprate" => 2 ),
                array( "itemid" => 4947, "droprate" => 150 ),
                array( "itemid" => 776, "droprate" => 7 ),
                array( "itemid" => 4858, "droprate" => 250 ),
                array( "itemid" => 4174, "droprate" => 10 ),
                array( "itemid" => 4717, "droprate" => 250 ),
                array( "itemid" => 4172, "droprate" => 2 ),
                array( "itemid" => 748, "droprate" => 182 ),
                array( "itemid" => 749, "droprate" => 133 ),
                array( "itemid" => 793, "droprate" => 15 ),
                array( "itemid" => 811, "droprate" => 10 ),
                array( "itemid" => 788, "droprate" => 27 ),
                array( "itemid" => 798, "droprate" => 20 ),
                array( "itemid" => 772, "droprate" => 7 ),
                array( "itemid" => 808, "droprate" => 15 ),
                array( "itemid" => 815, "droprate" => 15 ),
                array( "itemid" => 699, "droprate" => 5 ),
                array( "itemid" => 701, "droprate" => 5 ),
                array( "itemid" => 775, "droprate" => 12 ),
            ),
            array(
                array( "itemid" => 1603, "droprate" => 1 ),
                array( "itemid" => 924, "droprate" => 1 ),
                array( "itemid" => 4898, "droprate" => 1 ),
                array( "itemid" => 790, "droprate" => 7 ),
                array( "itemid" => 773, "droprate" => 2 ),
            ),
        );
        $bcnms_master_table['under_observation'] = array(
            array(
                array("itemid" => 0, "droprate" => 910),   
            ),
            array(
                array("itemid" => 0, "droprate" => 467),   
                array("itemid" => 18086, "droprate" => 48),
                array("itemid" => 18046, "droprate" => 61),
                array("itemid" => 18210, "droprate" => 46),
                array("itemid" => 15286, "droprate" => 302),
                array("itemid" => 18350, "droprate" => 76),
            ),
            array(
                array("itemid" => 0, "droprate" => 413),   
                array("itemid" => 17696, "droprate" => 42),
                array("itemid" => 17936, "droprate" => 77),
                array("itemid" => 17693, "droprate" => 73),
                array("itemid" => 15287, "droprate" => 258),
                array("itemid" => 4717, "droprate" => 68), 
                array("itemid" => 4947, "droprate" => 55), 
                array("itemid" => 4858, "droprate" => 14), 
            ),
            array(
                array("itemid" => 4858, "droprate" => 114),
                array("itemid" => 4717, "droprate" => 174),
                array("itemid" => 4947, "droprate" => 138),
                array("itemid" => 769, "droprate" => 16),  
                array("itemid" => 770, "droprate" => 17),  
                array("itemid" => 771, "droprate" => 17),  
                array("itemid" => 772, "droprate" => 18),  
                array("itemid" => 773, "droprate" => 17),  
                array("itemid" => 774, "droprate" => 16),  
                array("itemid" => 775, "droprate" => 18),  
                array("itemid" => 776, "droprate" => 16),  
                array("itemid" => 749, "droprate" => 102), 
                array("itemid" => 748, "droprate" => 120), 
                array("itemid" => 699, "droprate" => 22),  
                array("itemid" => 811, "droprate" => 18),  
                array("itemid" => 793, "droprate" => 18),  
                array("itemid" => 790, "droprate" => 20),  
                array("itemid" => 808, "droprate" => 19),  
                array("itemid" => 792, "droprate" => 21),  
                array("itemid" => 788, "droprate" => 35),  
                array("itemid" => 815, "droprate" => 17),  
                array("itemid" => 798, "droprate" => 23),  
                array("itemid" => 4172, "droprate" => 21), 
                array("itemid" => 4174, "droprate" => 16), 
            ),
            array(
                array("itemid" => 4896, "droprate" => 116),
                array("itemid" => 4874, "droprate" => 113),
                array("itemid" => 4751, "droprate" => 137),
                array("itemid" => 4858, "droprate" => 67), 
                array("itemid" => 4714, "droprate" => 99), 
                array("itemid" => 811, "droprate" => 58),  
                array("itemid" => 793, "droprate" => 52),  
                array("itemid" => 790, "droprate" => 51),  
                array("itemid" => 808, "droprate" => 65),  
                array("itemid" => 792, "droprate" => 61),  
                array("itemid" => 788, "droprate" => 63),  
                array("itemid" => 815, "droprate" => 55),  
                array("itemid" => 798, "droprate" => 62),  
            ),
            array(
                array("itemid" => 939, "droprate" => 1000),
            ),
            array(
                array("itemid" => 914, "droprate" => 1000),
            ),
        );
        $bcnms_master_table['undying_promise'] = array(
            array(
                array( "itemid" =>   880, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>   880, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 17994, "droprate" =>  175),
                array( "itemid" => 12405, "droprate" =>  175),
                array( "itemid" => 17995, "droprate" =>  175),
                array( "itemid" => 17821, "droprate" =>  175),
                array( "itemid" => 17787, "droprate" =>  175),
                array( "itemid" =>   702, "droprate" =>  125),
            ),
            array(
                array( "itemid" => 18086, "droprate" =>  200),
                array( "itemid" => 12404, "droprate" =>  200),
                array( "itemid" => 18046, "droprate" =>  200),
                array( "itemid" => 18210, "droprate" =>  200),
                array( "itemid" => 18350, "droprate" =>  200),
            ),
            array(
                array( "itemid" =>   645, "droprate" =>   60),
                array( "itemid" =>   745, "droprate" =>   60),
                array( "itemid" =>   748, "droprate" =>   60),
                array( "itemid" =>   749, "droprate" =>   60),
                array( "itemid" =>   653, "droprate" =>   60),
                array( "itemid" =>   746, "droprate" =>   60),
                array( "itemid" =>   895, "droprate" =>   60),
                array( "itemid" =>  4717, "droprate" =>  125),
                array( "itemid" =>  4172, "droprate" =>  145),
                array( "itemid" =>  4947, "droprate" =>  125),
                array( "itemid" =>  4858, "droprate" =>  125),
                array( "itemid" =>   866, "droprate" =>   60),
            ),
            array(
                array( "itemid" =>   887, "droprate" =>   78),
                array( "itemid" =>   654, "droprate" =>   78),
                array( "itemid" =>   902, "droprate" =>   78),
                array( "itemid" =>  4896, "droprate" =>  125),
                array( "itemid" =>   737, "droprate" =>   78),
                array( "itemid" =>   653, "droprate" =>   78),
                array( "itemid" =>   703, "droprate" =>   78),
                array( "itemid" =>   895, "droprate" =>   78),
                array( "itemid" =>  4874, "droprate" =>  125),
                array( "itemid" =>  4751, "droprate" =>  125),
                array( "itemid" =>  4714, "droprate" =>  125),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  850),
                array( "itemid" =>   859, "droprate" =>   50),
                array( "itemid" =>   700, "droprate" =>   50),
                array( "itemid" =>   738, "droprate" =>   50),
            ),
        );
        $bcnms_master_table['steamed sprouts'] = array(
            array(
                array( "itemid" =>   748, "droprate" =>  500 ), 
                array( "itemid" =>   749, "droprate" =>  500 ), 
            ),      
            array(
                array( "itemid" =>     0, "droprate" =>  750 ), 
                array( "itemid" =>  4174, "droprate" =>  250 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  600 ), 
                array( "itemid" => 13237, "droprate" =>  100 ), 
                array( "itemid" => 13127, "droprate" =>  100 ), 
                array( "itemid" => 13405, "droprate" =>  100 ), 
                array( "itemid" => 12349, "droprate" =>  100 ), 
            ),
            array(
                array( "itemid" =>   776, "droprate" =>  125 ), 
                array( "itemid" =>   773, "droprate" =>  125 ), 
                array( "itemid" =>   774, "droprate" =>  125 ), 
                array( "itemid" =>   769, "droprate" =>  125 ), 
                array( "itemid" =>   770, "droprate" =>  125 ), 
                array( "itemid" =>   771, "droprate" =>  125 ), 
                array( "itemid" =>   772, "droprate" =>  125 ), 
                array( "itemid" =>   775, "droprate" =>  125 ), 
            ),
            array(
                array( "itemid" =>   790, "droprate" =>   50 ), 
                array( "itemid" =>   793, "droprate" =>   50 ), 
                array( "itemid" =>   811, "droprate" =>   50 ), 
                array( "itemid" =>   797, "droprate" =>   50 ), 
                array( "itemid" =>   792, "droprate" =>   50 ), 
                array( "itemid" =>   699, "droprate" =>  100 ), 
                array( "itemid" =>   808, "droprate" =>  100 ), 
                array( "itemid" =>   815, "droprate" =>  100 ), 
                array( "itemid" =>   701, "droprate" =>  100 ), 
                array( "itemid" =>   798, "droprate" =>  100 ), 
                array( "itemid" =>   794, "droprate" =>  100 ), 
                array( "itemid" =>   788, "droprate" =>  150 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  125 ), 
                array( "itemid" =>  4717, "droprate" =>  125 ), 
                array( "itemid" =>  4896, "droprate" =>  125 ), 
                array( "itemid" =>  4751, "droprate" =>  125 ), 
                array( "itemid" =>  4874, "droprate" =>  125 ), 
                array( "itemid" =>  4714, "droprate" =>  125 ), 
                array( "itemid" =>  4858, "droprate" =>  125 ), 
                array( "itemid" =>  4947, "droprate" =>  125 ), 
            ),
        );
        $bcnms_master_table['tails of woe'] = array(
            array(
                array( "itemid" => 13553, "droprate" => 150 ), 
                array( "itemid" => 0,     "droprate" => 850 ), 
            ),      
            array(
                array( "itemid" => 13554, "droprate" => 300 ), 
                array( "itemid" => 13625, "droprate" => 200 ), 
                array( "itemid" => 13238, "droprate" => 200 ), 
                array( "itemid" => 0,     "droprate" => 300 ), 
            ),
            array(
                array( "itemid" => 4896, "droprate" => 145 ), 
                array( "itemid" => 4751, "droprate" => 165 ), 
                array( "itemid" => 4714, "droprate" => 140 ), 
                array( "itemid" => 4874, "droprate" => 123 ), 
                array( "itemid" => 788,  "droprate" =>  94 ), 
                array( "itemid" => 792,  "droprate" =>  94 ), 
            ),
            array(
                array( "itemid" => 4751, "droprate" => 125 ), 
                array( "itemid" => 4714, "droprate" => 110 ), 
                array( "itemid" => 4874, "droprate" => 104 ), 
                array( "itemid" => 788,  "droprate" =>  94 ), 
                array( "itemid" => 792,  "droprate" =>  94 ), 
                array( "itemid" => 0,    "droprate" =>  94 ), 
            ),
            array(
                array( "itemid" => 4896, "droprate" => 174 ), 
                array( "itemid" => 4751, "droprate" =>  16 ), 
                array( "itemid" => 4714, "droprate" => 114 ), 
                array( "itemid" => 4874, "droprate" => 174 ), 
                array( "itemid" => 4947, "droprate" => 138 ), 
                array( "itemid" => 4172, "droprate" =>  21 ), 
                array( "itemid" => 792,  "droprate" =>  21 ), 
            ),
            array(
                array( "itemid" => 4714, "droprate" => 87 ), 
                array( "itemid" => 4874, "droprate" => 75 ), 
                array( "itemid" => 4947, "droprate" => 75 ), 
                array( "itemid" =>  792, "droprate" => 86 ), 
                array( "itemid" =>    0, "droprate" =>  0 ), 
            ),
        );
        $bcnms_master_table['the worms turn'] = array(
            array(
                array( "itemid" =>     0, "droprate" =>  125 ), 
                array( "itemid" =>  4896, "droprate" =>  125 ), 
                array( "itemid" =>  4714, "droprate" =>  125 ), 
                array( "itemid" =>  4947, "droprate" =>  125 ), 
                array( "itemid" =>  4751, "droprate" =>  125 ), 
                array( "itemid" =>  4858, "droprate" =>  125 ), 
                array( "itemid" =>  4874, "droprate" =>  125 ), 
                array( "itemid" =>  4717, "droprate" =>  125 ), 
            ),      
            array(
                array( "itemid" =>     0, "droprate" =>  125 ), 
                array( "itemid" => 13405, "droprate" =>  125 ), 
                array( "itemid" => 13129, "droprate" =>  125 ), 
                array( "itemid" => 13127, "droprate" =>  125 ), 
                array( "itemid" => 13404, "droprate" =>  125 ), 
                array( "itemid" => 13623, "droprate" =>  125 ), 
                array( "itemid" => 12350, "droprate" =>  125 ), 
                array( "itemid" => 17203, "droprate" =>  125 ), 
            ),
            array(
                array( "itemid" =>   699, "droprate" =>  500 ), 
                array( "itemid" =>   701, "droprate" =>  500 ), 
            ),
            array(
                array( "itemid" =>   748, "droprate" =>  500 ), 
                array( "itemid" =>   749, "droprate" =>  500 ), 
            ),
            array(
                array( "itemid" =>   793, "droprate" =>  200 ), 
                array( "itemid" =>   811, "droprate" =>  200 ), 
                array( "itemid" =>   771, "droprate" =>  200 ), 
                array( "itemid" =>   788, "droprate" =>  200 ), 
                array( "itemid" =>   798, "droprate" =>  200 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  800 ), 
                array( "itemid" =>  4172, "droprate" =>  200 ), 
            ),
        );
    // BCNM 50
        $bcnms_master_table['3,2,1'] = array(
            array(
                array( "itemid" => 16897, "droprate" =>  500 ), 
                array( "itemid" => 16991, "droprate" =>  500 ), 
            ),
            array(
                array( "itemid" => 13251, "droprate" =>  200 ), 
                array( "itemid" => 13252, "droprate" =>  200 ), 
                array( "itemid" => 13253, "droprate" =>  200 ), 
                array( "itemid" => 13254, "droprate" =>  200 ), 
                array( "itemid" => 13255, "droprate" =>  200 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  250 ), 
                array( "itemid" =>  4814, "droprate" =>  125 ), 
                array( "itemid" =>  4818, "droprate" =>  125 ), 
                array( "itemid" =>  4621, "droprate" =>  125 ), 
                array( "itemid" =>  4719, "droprate" =>  125 ), 
                array( "itemid" =>  4896, "droprate" =>  125 ), 
                array( "itemid" =>  4902, "droprate" =>  125 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  800 ), 
                array( "itemid" =>   703, "droprate" =>  200 ), 
            ),
        );
        $bcnms_master_table['treasure and tribulation'] = array(
            array(
                array( "itemid" => 13292, "droprate" =>   75 ), 
                array( "itemid" => 13287, "droprate" =>   32 ), 
                array( "itemid" => 13300, "droprate" =>   54 ), 
                array( "itemid" => 13298, "droprate" =>   32 ), 
                array( "itemid" => 13293, "droprate" =>   97 ), 
                array( "itemid" => 13289, "droprate" =>   75 ), 
                array( "itemid" => 13286, "droprate" =>  108 ), 
                array( "itemid" => 13294, "droprate" =>   22 ), 
                array( "itemid" => 13296, "droprate" =>   65 ), 
                array( "itemid" => 13299, "droprate" =>   32 ), 
                array( "itemid" => 13290, "droprate" =>   32 ), 
                array( "itemid" => 13295, "droprate" =>   86 ), 
                array( "itemid" => 13288, "droprate" =>   86 ), 
                array( "itemid" => 13291, "droprate" =>   75 ), 
                array( "itemid" => 13297, "droprate" =>   11 ), 
                array( "itemid" => 13447, "droprate" =>   32 ), 
            ),
            array(
                array( "itemid" => 13447, "droprate" =>   22 ), 
                array( "itemid" =>  4818, "droprate" =>   65 ), 
                array( "itemid" =>   859, "droprate" =>   10 ), 
                array( "itemid" =>  4172, "droprate" =>   11 ), 
                array( "itemid" =>   653, "droprate" =>   22 ), 
                array( "itemid" =>  4902, "droprate" =>   10 ), 
                array( "itemid" =>  4814, "droprate" =>   32 ), 
                array( "itemid" =>  4719, "droprate" =>   43 ), 
                array( "itemid" =>  4621, "droprate" =>   32 ), 
                array( "itemid" =>   703, "droprate" =>   11 ), 
                array( "itemid" =>   887, "droprate" =>   11 ), 
                array( "itemid" =>   700, "droprate" =>   11 ), 
                array( "itemid" =>   738, "droprate" =>   43 ), 
                array( "itemid" =>   737, "droprate" =>  108 ), 
                array( "itemid" =>   645, "droprate" =>   32 ), 
                array( "itemid" =>   644, "droprate" =>   65 ), 
                array( "itemid" =>   745, "droprate" =>   10 ), 
                array( "itemid" =>   654, "droprate" =>   11 ), 
                array( "itemid" =>   746, "droprate" =>   11 ), 
                array( "itemid" =>   702, "droprate" =>   11 ), 
                array( "itemid" =>   895, "droprate" =>   11 ), 
                array( "itemid" =>   902, "droprate" =>   11 ), 
                array( "itemid" =>  1116, "droprate" =>    9 ), 
                array( "itemid" =>  1122, "droprate" =>   11 ), 
                array( "itemid" =>   866, "droprate" =>   11 ), 
            ),
        );
    // BCNM 60
        $bcnms_master_table['amphibian_assault'] = array(
            array(
                array( "itemid" => 13155, "droprate" =>  250),
                array( "itemid" => 13152, "droprate" =>  250),
                array( "itemid" => 13150, "droprate" =>  250),
                array( "itemid" => 13160, "droprate" =>  250),
            ),
            array(
                array( "itemid" => 13156, "droprate" =>  250),
                array( "itemid" => 13148, "droprate" =>  250),
                array( "itemid" => 13151, "droprate" =>  250),
                array( "itemid" => 13154, "droprate" =>  250),
            ),
            array(
                array( "itemid" =>  1260, "droprate" =>  125),
                array( "itemid" =>  1257, "droprate" =>  125),
                array( "itemid" =>  1256, "droprate" =>  125),
                array( "itemid" =>  1259, "droprate" =>  125),
                array( "itemid" =>  1261, "droprate" =>  125),
                array( "itemid" =>  1255, "droprate" =>  125),
                array( "itemid" =>  1262, "droprate" =>  125),
                array( "itemid" =>  1258, "droprate" =>  125),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  750),
                array( "itemid" => 13158, "droprate" =>  250),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  200),
                array( "itemid" =>   751, "droprate" =>  800),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  375),
                array( "itemid" =>  4896, "droprate" =>  125),
                array( "itemid" =>  4874, "droprate" =>  125),
                array( "itemid" =>  4751, "droprate" =>  125),
                array( "itemid" =>  4714, "droprate" =>  125),
                array( "itemid" =>  4621, "droprate" =>  125),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  888),
                array( "itemid" =>  4175, "droprate" =>   56),
                array( "itemid" =>  4173, "droprate" =>   56),
            ),
            array(
                array( "itemid" =>   810, "droprate" =>   10),
                array( "itemid" =>   797, "droprate" =>   50),
                array( "itemid" =>   803, "droprate" =>   10),
                array( "itemid" =>   784, "droprate" =>  150),
                array( "itemid" =>   791, "droprate" =>   50),
                array( "itemid" =>   802, "droprate" =>  150),
                array( "itemid" =>   771, "droprate" =>   50),
                array( "itemid" =>   769, "droprate" =>   50),
                array( "itemid" =>   776, "droprate" =>  100),
                array( "itemid" =>   772, "droprate" =>   50),
                array( "itemid" =>   773, "droprate" =>  100),
                array( "itemid" =>   801, "droprate" =>  150),
                array( "itemid" =>   775, "droprate" =>   50),
                array( "itemid" =>   774, "droprate" =>   50),
            ),
            array(
                array( "itemid" =>   751, "droprate" =>  500),
                array( "itemid" =>   887, "droprate" =>  222),
                array( "itemid" =>   837, "droprate" =>   10),
                array( "itemid" =>   652, "droprate" =>  111),
                array( "itemid" =>   702, "droprate" =>   56),
            ),
        );
        $bcnms_master_table['jungle_boogymen'] = array(
            array(
                array( "itemid" => 13153, "droprate" => 250),
                array( "itemid" => 13156, "droprate" => 250),
                array( "itemid" => 13157, "droprate" => 250),
                array( "itemid" => 13161, "droprate" => 250),
            ),
            array(
                array( "itemid" => 751, "droprate" => 500),  
                array( "itemid" => 4874, "droprate" => 48),  
                array( "itemid" => 4751, "droprate" => 143), 
                array( "itemid" => 4714, "droprate" => 119), 
                array( "itemid" => 4896, "droprate" => 48),  
                array( "itemid" => 1255, "droprate" => 48),  
                array( "itemid" => 1256, "droprate" => 48),  
                array( "itemid" => 1257, "droprate" => 48),  
                array( "itemid" => 1258, "droprate" => 48),  
                array( "itemid" => 1259, "droprate" => 48),  
                array( "itemid" => 1260, "droprate" => 48),  
                array( "itemid" => 1261, "droprate" => 48),  
                array( "itemid" => 1262, "droprate" => 48),  
            ),
            array(
                array( "itemid" => 751, "droprate" => 833),  
                array( "itemid" => 1256, "droprate" => 167), 
            ),
            array(
                array( "itemid" => 13155, "droprate" => 250),
                array( "itemid" => 13148, "droprate" => 250),
                array( "itemid" => 13151, "droprate" => 250),
                array( "itemid" => 13158, "droprate" => 250),
            ),
            array(
                array( "itemid" => 654, "droprate" => 154),  
                array( "itemid" => 797, "droprate" => 154),  
                array( "itemid" => 745, "droprate" => 154),  
                array( "itemid" => 791, "droprate" => 77),   
                array( "itemid" => 4175, "droprate" => 77),  
                array( "itemid" => 653, "droprate" => 153),  
                array( "itemid" => 801, "droprate" => 30),   
                array( "itemid" => 802, "droprate" => 30),   
                array( "itemid" => 803, "droprate" => 30),   
                array( "itemid" => 805, "droprate" => 30),   
                array( "itemid" => 791, "droprate" => 30),   
                array( "itemid" => 702, "droprate" => 30),   
                array( "itemid" => 700, "droprate" => 30),   
                array( "itemid" => 942, "droprate" => 30),   
            ),
            array(
                array( "itemid" => 654, "droprate" => 77),   
                array( "itemid" => 802, "droprate" => 134),  
                array( "itemid" => 652, "droprate" => 154),  
                array( "itemid" => 801, "droprate" => 50),   
                array( "itemid" => 4173, "droprate" => 154), 
                array( "itemid" => 784, "droprate" => 121),  
                array( "itemid" => 837, "droprate" => 10),   
                array( "itemid" => 1110, "droprate" => 10),  
                array( "itemid" => 769, "droprate" => 30),   
                array( "itemid" => 770, "droprate" => 30),   
                array( "itemid" => 771, "droprate" => 30),   
                array( "itemid" => 772, "droprate" => 30),   
                array( "itemid" => 773, "droprate" => 30),   
                array( "itemid" => 774, "droprate" => 30),   
                array( "itemid" => 775, "droprate" => 30),   
                array( "itemid" => 776, "droprate" => 30),   
                array( "itemid" => 810, "droprate" => 50),   
            ),
        );
        $bcnms_master_table['up_in_arms'] = array(
            array(
                array( "itemid" => 65535, "droprate" => 1000, "amount" => 15000),
            ),
            array(
                array( "itemid" => 793, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 792, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 792, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 1311, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 1311, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 1311, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 14666, "droprate" => 447),
                array( "itemid" => 14662, "droprate" => 487),
            ),
            array(
                array( "itemid" => 13175, "droprate" => 494),
                array( "itemid" => 13176, "droprate" => 449),
            ),
            array(
                array( "itemid" => 791, "droprate" => 51),  
                array( "itemid" => 801, "droprate" => 32),  
                array( "itemid" => 654, "droprate" => 39),  
                array( "itemid" => 702, "droprate" => 21),  
                array( "itemid" => 4173, "droprate" => 32), 
                array( "itemid" => 745, "droprate" => 55),  
                array( "itemid" => 784, "droprate" => 62),  
                array( "itemid" => 653, "droprate" => 81),  
                array( "itemid" => 802, "droprate" => 56),  
                array( "itemid" => 797, "droprate" => 195), 
                array( "itemid" => 652, "droprate" => 58),  
                array( "itemid" => 803, "droprate" => 38),  
                array( "itemid" => 773, "droprate" => 11),  
                array( "itemid" => 4175, "droprate" => 21), 
                array( "itemid" => 771, "droprate" => 15),  
                array( "itemid" => 805, "droprate" => 26),  
                array( "itemid" => 769, "droprate" => 21),  
                array( "itemid" => 700, "droprate" => 17),  
                array( "itemid" => 770, "droprate" => 9),   
                array( "itemid" => 810, "droprate" => 62),  
                array( "itemid" => 774, "droprate" => 11),  
                array( "itemid" => 775, "droprate" => 11),  
                array( "itemid" => 772, "droprate" => 11),  
                array( "itemid" => 776, "droprate" => 9),   
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  932),
                array( "itemid" => 15185, "droprate" =>   55),
            ),
        );
        $bcnms_master_table['wild_wild_whiskers'] = array(
            array(
                array( "itemid" =>  1591, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>  1591, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>  1591, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>   646, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>  5253, "droprate" => 1000),
            ),
            array(
                array( "itemid" =>  4213, "droprate" => 1000),
            ),
            array(
                array( "itemid" => 15293, "droprate" =>  365),
                array( "itemid" => 15292, "droprate" =>  635),
            ),
            array(
                array( "itemid" => 14663, "droprate" =>  426),
                array( "itemid" => 14665, "droprate" =>  574),
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  848),
                array( "itemid" => 15185, "droprate" =>   58),
                array( "itemid" =>  4173, "droprate" =>   78),
                array( "itemid" =>   702, "droprate" =>   16),
            ),
            array(
                array( "itemid" =>   771, "droprate" =>    9),
                array( "itemid" =>   775, "droprate" =>    9),
                array( "itemid" =>   791, "droprate" =>   16),
                array( "itemid" =>   769, "droprate" =>   16),
                array( "itemid" =>   770, "droprate" =>   16),
                array( "itemid" =>   774, "droprate" =>   16),
                array( "itemid" =>   700, "droprate" =>   33),
                array( "itemid" =>   801, "droprate" =>   33),
                array( "itemid" =>   805, "droprate" =>   33),
                array( "itemid" =>   652, "droprate" =>   49),
                array( "itemid" =>   654, "droprate" =>   49),
                array( "itemid" =>   773, "droprate" =>   49),
                array( "itemid" =>   803, "droprate" =>   49),
                array( "itemid" =>   802, "droprate" =>   66),
                array( "itemid" =>   653, "droprate" =>   82),
                array( "itemid" =>   810, "droprate" =>   82),
                array( "itemid" =>   745, "droprate" =>   98),
                array( "itemid" =>   784, "droprate" =>   98),
                array( "itemid" =>   797, "droprate" =>   98),
                array( "itemid" =>  4175, "droprate" =>   99),
            ),
        );
        $bcnms_master_table['dismemberment_brigade'] = array(
            array(
                array( "itemid" => 16684, "droprate" =>  250 ), 
                array( "itemid" => 17190, "droprate" =>  250 ), 
                array( "itemid" => 17648, "droprate" =>  250 ), 
                array( "itemid" => 17379, "droprate" =>  250 ), 
            ),      
            array(
                array( "itemid" =>     0, "droprate" =>  400 ), 
                array( "itemid" => 13128, "droprate" =>  200 ), 
                array( "itemid" => 13403, "droprate" =>  200 ), 
                array( "itemid" => 13555, "droprate" =>  200 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  200 ), 
                array( "itemid" =>   773, "droprate" =>  200 ), 
                array( "itemid" =>   772, "droprate" =>  200 ), 
                array( "itemid" =>   771, "droprate" =>  200 ), 
                array( "itemid" =>   774, "droprate" =>  200 ), 
            ),
            array(
                array( "itemid" =>   797, "droprate" =>  100 ), 
                array( "itemid" =>   784, "droprate" =>  100 ), 
                array( "itemid" =>   653, "droprate" =>  100 ), 
                array( "itemid" =>   652, "droprate" =>  100 ), 
                array( "itemid" =>   810, "droprate" =>  100 ), 
                array( "itemid" =>   745, "droprate" =>  100 ), 
                array( "itemid" =>   805, "droprate" =>  100 ), 
                array( "itemid" =>   801, "droprate" =>  100 ), 
                array( "itemid" =>   654, "droprate" =>  100 ), 
                array( "itemid" =>   802, "droprate" =>  100 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  900 ), 
                array( "itemid" =>  4175, "droprate" =>  100 ), 
            ),
        );
        $bcnms_master_table['legion_XI_comitatensis'] = array(
            array(  
                array( "itemid" => 13149, "droprate" =>  250 ), 
                array( "itemid" => 13148, "droprate" =>  250 ), 
                array( "itemid" => 13159, "droprate" =>  250 ), 
                array( "itemid" => 13156, "droprate" =>  250 ), 
            ),
            array(
                array( "itemid" => 13154, "droprate" =>  250 ), 
                array( "itemid" => 13155, "droprate" =>  250 ), 
                array( "itemid" => 13152, "droprate" =>  250 ), 
                array( "itemid" => 13158, "droprate" =>  250 ), 
            ),
            array(
                array( "itemid" =>   803, "droprate" =>  100 ), 
                array( "itemid" =>   737, "droprate" =>  100 ), 
                array( "itemid" =>   644, "droprate" =>  100 ), 
                array( "itemid" =>   784, "droprate" =>  100 ), 
                array( "itemid" =>   810, "droprate" =>  100 ), 
                array( "itemid" =>   805, "droprate" =>  100 ), 
                array( "itemid" =>   801, "droprate" =>  100 ), 
                array( "itemid" =>   802, "droprate" =>  100 ), 
                array( "itemid" =>   797, "droprate" =>  100 ), 
                array( "itemid" =>   771, "droprate" =>   50 ), 
                array( "itemid" =>   776, "droprate" =>   50 ), 
            ),
            array(
                array( "itemid" =>     0, "droprate" =>  500 ), 
                array( "itemid" =>  4621, "droprate" =>  500 ), 
            ),
            array(
                array( "itemid" => 65535, "droprate" => 1000, "amount" => 18000 ),  

            ),
            array(
                array( "itemid" =>     0, "droprate" =>  950 ), 
                array( "itemid" =>  4175, "droprate" =>   50 ), 
            ),
            array(
                array( "itemid" =>   702, "droprate" =>  235 ), 
                array( "itemid" =>   654, "droprate" =>  235 ), 
                array( "itemid" =>   652, "droprate" =>  240 ), 
                array( "itemid" =>   653, "droprate" =>  240 ), 
                array( "itemid" =>   836, "droprate" =>   50 ), 
            ),
            array(
                array( "itemid" =>   751, "droprate" =>  600 ), 
                array( "itemid" =>  1260, "droprate" =>   50 ), 
                array( "itemid" =>  1257, "droprate" =>   50 ), 
                array( "itemid" =>  1256, "droprate" =>   50 ), 
                array( "itemid" =>  1259, "droprate" =>   50 ), 
                array( "itemid" =>  1261, "droprate" =>   50 ),
                array( "itemid" =>  1255, "droprate" =>   50 ),
                array( "itemid" =>  1262, "droprate" =>   50 ),
                array( "itemid" =>  1258, "droprate" =>   50 ),
            ),
        );
    // KSNM
        $bcnms_master_table['double_dragonian'] = array(
            array(
                array( "itemid" => 18378, "droprate" => 222 ),
                array( "itemid" => 17699, "droprate" => 302 ),
                array( "itemid" => 17509, "droprate" => 245 ),
                array( "itemid" => 18005, "droprate" => 208 ),
            ),
            array(
                array( "itemid" => 0, "droprate" => 638 ),    
                array( "itemid" => 1133, "droprate" => 10 ),  
                array( "itemid" => 4486, "droprate" => 176 ), 
                array( "itemid" => 4272, "droprate" => 176 ), 
            ),
            array(
                array( "itemid" => 0, "droprate" => 638 ),    
                array( "itemid" => 1133, "droprate" => 10 ),  
                array( "itemid" => 4486, "droprate" => 176 ), 
                array( "itemid" => 4272, "droprate" => 176 ), 
            ),
            array(
                array( "itemid" => 0, "droprate" => 392 ),    
                array( "itemid" => 19026, "droprate" => 354 ),
                array( "itemid" => 19024, "droprate" => 165 ),
                array( "itemid" => 19025, "droprate" => 89 ), 
            ),
            array(
                array( "itemid" => 14764, "droprate" => 586 ),
                array( "itemid" => 655, "droprate" => 184 ),  
                array( "itemid" => 747, "droprate" => 207 ),  
            ),
            array(
                array( "itemid" => 17842, "droprate" => 238 ),
                array( "itemid" => 14762, "droprate" => 250 ),
                array( "itemid" => 17700, "droprate" => 225 ),
                array( "itemid" => 18006, "droprate" => 275 ),
            ),
            array(
                array( "itemid" => 737, "droprate" => 122 ),  
                array( "itemid" => 4172, "droprate" => 54 ),  
                array( "itemid" => 644, "droprate" => 41 ),   
                array( "itemid" => 902, "droprate" => 81 ),   
                array( "itemid" => 702, "droprate" => 149 ),  
                array( "itemid" => 866, "droprate" => 54 ),   
                array( "itemid" => 4175, "droprate" => 27 ),  
                array( "itemid" => 700, "droprate" => 41 ),   
                array( "itemid" => 887, "droprate" => 95 ),   
                array( "itemid" => 703, "droprate" => 108 ),  
                array( "itemid" => 844, "droprate" => 135 ),  
                array( "itemid" => 738, "droprate" => 54 ),   
                array( "itemid" => 895, "droprate" => 14 ),   
                array( "itemid" => 830, "droprate" => 14 ),   
                array( "itemid" => 645, "droprate" => 68 ),   
                array( "itemid" => 4173, "droprate" => 14 ),  
                array( "itemid" => 1132, "droprate" => 135 ), 
            ),
            array(
                array( "itemid" => 836, "droprate" => 96 ),   
                array( "itemid" => 658, "droprate" => 27 ),   
                array( "itemid" => 942, "droprate" => 164 ),  
                array( "itemid" => 844, "droprate" => 260 ),  
                array( "itemid" => 837, "droprate" => 96 ),   
                array( "itemid" => 1132, "droprate" => 288 ), 
                array( "itemid" => 1110, "droprate" => 41 ),  
            ),
        );
        $bcnms_master_table['eye_of_the_storm'] = array(
            array(
                array( "itemid" => 1124, "droprate" => 1000 ),
            ),
            array(
                array( "itemid" => 1122, "droprate" => 1000 ),
            ),
            array(
                array( "itemid" => 65535, "droprate" => 1000, "amount" => 24000 ), 
            ),
            array(
                array( "itemid" => 836, "droprate" => 216 ),
                array( "itemid" => 658, "droprate" => 295 ),
                array( "itemid" => 17938, "droprate" => 239 ),
                array( "itemid" => 17998, "droprate" => 231 ),
                array( "itemid" => 17579, "droprate" => 231 ),
                array( "itemid" => 18373, "droprate" => 231 ),
                array( "itemid" => 1110, "droprate" => 231 ),
            ),
            array(
                array( "itemid" => 18092, "droprate" => 104 ),
                array( "itemid" => 4175, "droprate" => 86 ),
                array( "itemid" => 4174, "droprate" => 22 ),
                array( "itemid" => 19025, "droprate" => 146 ),
                array( "itemid" => 19024, "droprate" => 240 ),
            ),
            array(
                array( "itemid" => 17246, "droprate" => 287 ),
                array( "itemid" => 17790, "droprate" => 216 ),
                array( "itemid" => 17999, "droprate" => 198 ),
                array( "itemid" => 18089, "droprate" => 287 ),
                array( "itemid" => 4774, "droprate" => 287 ),
            ),
            array(
                array( "itemid" => 887, "droprate" => 52 ),
                array( "itemid" => 645, "droprate" => 56 ),
                array( "itemid" => 902, "droprate" => 41 ),
                array( "itemid" => 702, "droprate" => 63 ),
                array( "itemid" => 737, "droprate" => 52 ),
                array( "itemid" => 823, "droprate" => 26 ),
                array( "itemid" => 1465, "droprate" => 11 ),
                array( "itemid" => 4173, "droprate" => 37 ),
                array( "itemid" => 700, "droprate" => 101 ),
                array( "itemid" => 653, "droprate" => 30 ),
                array( "itemid" => 644, "droprate" => 52 ),
                array( "itemid" => 703, "droprate" => 116 ),
                array( "itemid" => 844, "droprate" => 15 ),
                array( "itemid" => 942, "droprate" => 56 ),
                array( "itemid" => 738, "droprate" => 45 ),
                array( "itemid" => 830, "droprate" => 22 ),
                array( "itemid" => 895, "droprate" => 67 ),
                array( "itemid" => 1132, "droprate" => 119 ),
                array( "itemid" => 4172, "droprate" => 45 ),
                array( "itemid" => 0, "droprate" => 400)
            ),
            array(
                array( "itemid" => 836, "droprate" => 56 ),
                array( "itemid" => 658, "droprate" => 93 ),
                array( "itemid" => 837, "droprate" => 56 ),
                array( "itemid" => 942, "droprate" => 157 ),
                array( "itemid" => 844, "droprate" => 176 ),
                array( "itemid" => 1132, "droprate" => 109 ),
                array( "itemid" => 0, "droprate" => 500 ),
            )
        );
        $bcnms_master_table['operation_desert_swarm'] = array(
            array(
                array( "itemid" => 1473, "droprate" => 813 ),
                array( "itemid" => 13552, "droprate" => 55 ),
                array( "itemid" => 901, "droprate" => 123 ),
            ),      
            array(
                array( "itemid" => 17207, "droprate" => 216 ),
                array( "itemid" => 18005, "droprate" => 295 ),
                array( "itemid" => 18217, "droprate" => 239 ),
                array( "itemid" => 17793, "droprate" => 231 ),
            ),
            array(
                array( "itemid" => 17624, "droprate" => 504 ),
                array( "itemid" => 655, "droprate" => 4 ),
                array( "itemid" => 19027, "droprate" => 86 ),
                array( "itemid" => 747, "droprate" => 22 ),
                array( "itemid" => 19025, "droprate" => 146 ),
                array( "itemid" => 19024, "droprate" => 22 ),
            ),
            array(
                array( "itemid" => 15295, "droprate" => 287 ),
                array( "itemid" => 12407, "droprate" => 216 ),
                array( "itemid" => 14871, "droprate" => 198 ),
                array( "itemid" => 15294, "droprate" => 287 ),
            ),
            array(
                array( "itemid" => 887, "droprate" => 52 ),
                array( "itemid" => 645, "droprate" => 56 ),
                array( "itemid" => 902, "droprate" => 41 ),
                array( "itemid" => 702, "droprate" => 63 ),
                array( "itemid" => 737, "droprate" => 52 ),
                array( "itemid" => 823, "droprate" => 26 ),
                array( "itemid" => 1465, "droprate" => 11 ),
                array( "itemid" => 4173, "droprate" => 37 ),
                array( "itemid" => 700, "droprate" => 101 ),
                array( "itemid" => 653, "droprate" => 0 ),
                array( "itemid" => 644, "droprate" => 52 ),
                array( "itemid" => 703, "droprate" => 116 ),
                array( "itemid" => 844, "droprate" => 15 ),
                array( "itemid" => 942, "droprate" => 56 ),
                array( "itemid" => 738, "droprate" => 45 ),
                array( "itemid" => 830, "droprate" => 22 ),
                array( "itemid" => 895, "droprate" => 67 ),
                array( "itemid" => 1132, "droprate" => 119 ),
                array( "itemid" => 4172, "droprate" => 45 ),
                array( "itemid" => 4174, "droprate" => 19 ),
                array( "itemid" => 4175, "droprate" => 41 ),
                array( "itemid" => 866, "droprate" => 34 ),
            ),
            array(
                array( "itemid" => 1110, "droprate" => 78 ),
                array( "itemid" => 836, "droprate" => 56 ),
                array( "itemid" => 658, "droprate" => 93 ),
                array( "itemid" => 837, "droprate" => 56 ),
                array( "itemid" => 942, "droprate" => 157 ),
                array( "itemid" => 844, "droprate" => 276 ),
                array( "itemid" => 1132, "droprate" => 209 ),
            ),
        );
        $bcnms_master_table['early_bird_catches_the_worm'] = array(
            array(
                array( "itemid" => 1441, "droprate" => 312 ), 
                array( "itemid" => 17694, "droprate" => 182 ), 
                array( "itemid" => 18047, "droprate" => 65 ), 
                array( "itemid" => 17937, "droprate" => 43 ), 
                array( "itemid" => 18173, "droprate" => 181 ), 
                array( "itemid" => 17823, "droprate" => 217 ), 
                array( "itemid" => 17575, "droprate" => 43 ), 
            ),
            array(
                array( "itemid" => 1442, "droprate" => 159 ), 
                array( "itemid" => 17695, "droprate" => 151 ), 
                array( "itemid" => 18088, "droprate" => 167 ), 
                array( "itemid" => 17576, "droprate" => 95 ), 
                array( "itemid" => 17245, "droprate" => 95 ), 
                array( "itemid" => 17996, "droprate" => 56 ), 
                array( "itemid" => 17789, "droprate" => 341 ), 
            ),
            array(
                array( "itemid" => 4486, "droprate" => 522 ), 
                array( "itemid" => 4272, "droprate" => 346 ), 
            ),
            array(
                array( "itemid" => 887, "droprate" => 32 ),   
                array( "itemid" => 645, "droprate" => 71 ),   
                array( "itemid" => 902, "droprate" => 79 ),   
                array( "itemid" => 702, "droprate" => 56 ),   
                array( "itemid" => 737, "droprate" => 71 ),   
                array( "itemid" => 823, "droprate" => 32 ),   
                array( "itemid" => 4173, "droprate" => 48 ),  
                array( "itemid" => 700, "droprate" => 127 ),  
                array( "itemid" => 644, "droprate" => 111 ),  
                array( "itemid" => 703, "droprate" => 183 ),  
                array( "itemid" => 942, "droprate" => 40 ),   
                array( "itemid" => 738, "droprate" => 56 ),   
                array( "itemid" => 895, "droprate" => 24 ),   
                array( "itemid" => 1132, "droprate" => 119 ), 
                array( "itemid" => 4172, "droprate" => 56 ),  
                array( "itemid" => 4175, "droprate" => 40 ),  
                array( "itemid" => 866, "droprate" => 24 ),   
            ),
            array(
                array( "itemid" => 1526, "droprate" => 210 ), 
                array( "itemid" => 1313, "droprate" => 775 ), 
            ),
            array(
                array( "itemid" => 4209, "droprate" => 94 ),  
                array( "itemid" => 4207, "droprate" => 130 ), 
                array( "itemid" => 4211, "droprate" => 116 ), 
                array( "itemid" => 4213, "droprate" => 51 ),  
                array( "itemid" => 1132, "droprate" => 246 ), 
                array( "itemid" => 17582, "droprate" => 246 ), 
            ),
            array(
                array( "itemid" => 4135, "droprate" => 290 ), 
                array( "itemid" => 4119, "droprate" => 225 ), 
                array( "itemid" => 4173, "droprate" => 210 ), 
                array( "itemid" => 4175, "droprate" => 217 ), 
            ),
            array(
                array( "itemid" => 3339, "droprate" => 1000 ), 
            ),
            array(
                array( "itemid" => 1110, "droprate" => 58 ),  
                array( "itemid" => 836, "droprate" => 36 ),   
                array( "itemid" => 658, "droprate" => 72 ),   
                array( "itemid" => 837, "droprate" => 22 ),   
                array( "itemid" => 942, "droprate" => 275 ),  
                array( "itemid" => 844, "droprate" => 196 ),  
                array( "itemid" => 1132, "droprate" => 225 ), 
            ),
            array(
                array( "itemid" => 722, "droprate" => 94 ),   
                array( "itemid" => 1446, "droprate" => 196 ), 
                array( "itemid" => 703, "droprate" => 572 ),  
                array( "itemid" => 831, "droprate" => 43 ),   
            ),
        );
        $bcnms_master_table['horns_of_war'] = array(
            array(
                array( "itemid" => 1441, "droprate" => 158 ),  
                array( "itemid" => 17939, "droprate" => 263 ), 
                array( "itemid" => 17823, "droprate" => 92 ),  
                array( "itemid" => 18173, "droprate" => 79 ),  
                array( "itemid" => 17694, "droprate" => 66 ),  
                array( "itemid" => 17464, "droprate" => 105 ),  
                array( "itemid" => 18351, "droprate" => 237 ), 
            ),      
            array(
                array( "itemid" => 1442, "droprate" => 169 ),  
                array( "itemid" => 17789, "droprate" => 12 ),  
                array( "itemid" => 17838, "droprate" => 235 ), 
                array( "itemid" => 18088, "droprate" => 77 ),  
                array( "itemid" => 18211, "droprate" => 248 ), 
                array( "itemid" => 17578, "droprate" => 195 ), 
                array( "itemid" => 17695, "droprate" => 64 ),  
            ),
            array(
                array( "itemid" => 703, "droprate" => 556 ),   
                array( "itemid" => 1446, "droprate" => 289 ),  
                array( "itemid" => 831, "droprate" => 25 ),    
                array( "itemid" => 722, "droprate" => 130 ),   
            ),
            array(
                array( "itemid" => 860, "droprate" => 572 ),   
                array( "itemid" => 883, "droprate" => 428 ),   
            ),
            array(
                array( "itemid" => 902, "droprate" => 86 ),    
                array( "itemid" => 703, "droprate" => 47 ),    
                array( "itemid" => 1132, "droprate" => 47 ),   
                array( "itemid" => 830, "droprate" => 7 ),    
                array( "itemid" => 4173, "droprate" => 99 ),  
                array( "itemid" => 703, "droprate" => 179 ),   
                array( "itemid" => 942, "droprate" => 113 ),   
                array( "itemid" => 737, "droprate" => 47 ),    
                array( "itemid" => 644, "droprate" => 60 ),    
                array( "itemid" => 887, "droprate" => 47 ),    
                array( "itemid" => 700, "droprate" => 60 ),    
                array( "itemid" => 866, "droprate" => 20 ),    
                array( "itemid" => 645, "droprate" => 20 ),    
                array( "itemid" => 895, "droprate" => 47 ),    
                array( "itemid" => 702, "droprate" => 73 ),    
                array( "itemid" => 4172, "droprate" => 7 ),   
                array( "itemid" => 738, "droprate" => 20 ),    
                array( "itemid" => 4174, "droprate" => 20 ),   
                array( "itemid" => 4175, "droprate" => 1 ),    
            ),
            array(
                array( "itemid" => 1527, "droprate" => 199 ),  
                array( "itemid" => 883, "droprate" => 318 ),   
                array( "itemid" => 4199, "droprate" => 147 ),  
                array( "itemid" => 4201, "droprate" => 68 ),   
                array( "itemid" => 4205, "droprate" => 134 ),  
                array( "itemid" => 4203, "droprate" => 134 ),  
            ),
            array(
                array( "itemid" => 3341, "droprate" => 1000 ), 
            ),
            array(
                array( "itemid" => 4209, "droprate" => 172 ),  
                array( "itemid" => 4207, "droprate" => 80 ),   
                array( "itemid" => 4211, "droprate" => 106 ),  
                array( "itemid" => 4213, "droprate" => 172 ),  
                array( "itemid" => 17840, "droprate" => 239 ), 
                array( "itemid" => 785, "droprate" => 107 ),    
                array( "itemid" => 804, "droprate" => 41 ),    
                array( "itemid" => 786, "droprate" => 55 ),    
                array( "itemid" => 787, "droprate" => 28 ),    
            ),
            array(
                array( "itemid" => 4135, "droprate" => 289 ),  
                array( "itemid" => 4119, "droprate" => 237 ),  
                array( "itemid" => 4173, "droprate" => 198 ),  
                array( "itemid" => 4175, "droprate" => 276 ),  
            ),
            array(
                array( "itemid" => 887, "droprate" => 123 ),   
                array( "itemid" => 1132, "droprate" => 5 ),   
                array( "itemid" => 902, "droprate" => 98 ),   
                array( "itemid" => 737, "droprate" => 18 ),    
                array( "itemid" => 644, "droprate" => 71 ),    
                array( "itemid" => 4174, "droprate" => 44 ),   
                array( "itemid" => 895, "droprate" => 19 ),    
                array( "itemid" => 703, "droprate" => 280 ),   
                array( "itemid" => 738, "droprate" => 5 ),    
                array( "itemid" => 700, "droprate" => 45 ),    
                array( "itemid" => 866, "droprate" => 58 ),    
                array( "itemid" => 1465, "droprate" => 31 ),   
                array( "itemid" => 645, "droprate" => 30 ),    
                array( "itemid" => 702, "droprate" => 30 ),    
                array( "itemid" => 4173, "droprate" => 30 ),   
                array( "itemid" => 823, "droprate" => 96 ),   
                array( "itemid" => 830, "droprate" => 17 ),    
            ),
            array(
                array( "itemid" => 1132, "droprate" => 114 ),  
                array( "itemid" => 837, "droprate" => 50 ),    
                array( "itemid" => 942, "droprate" => 220 ),   
                array( "itemid" => 844, "droprate" => 404 ),   
                array( "itemid" => 836, "droprate" => 62 ),    
                array( "itemid" => 658, "droprate" => 49 ),    
                array( "itemid" => 1110, "droprate" => 101 ),   
            ),
        );
        $bcnms_master_table['sheep_in_antilons_clothing'] = array(
            array(
                array( "itemid" =>    0, "droprate" => 124),
                array( "itemid" => 1769, "droprate" => 268), 
                array( "itemid" => 1764, "droprate" => 266), 
                array( "itemid" => 1763, "droprate" => 342), 
            ),
            array(
                array( "itemid" =>    0, "droprate" => 944),
                array( "itemid" => 1842, "droprate" => 56),  
            ),
            array(
                array( "itemid" =>     0, "droprate" => 607),
                array( "itemid" => 17829, "droprate" => 70), 
                array( "itemid" => 17945, "droprate" => 78), 
                array( "itemid" => 17467, "droprate" => 52), 
                array( "itemid" => 13690, "droprate" => 90),
                array( "itemid" => 13109, "droprate" => 103),
            ),
            array(
                array( "itemid" =>     0, "droprate" => 935),
                array( "itemid" => 17829, "droprate" => 12), 
                array( "itemid" => 17945, "droprate" => 13), 
                array( "itemid" => 17467, "droprate" => 10), 
                array( "itemid" => 13690, "droprate" => 14),
                array( "itemid" => 13109, "droprate" => 16),
            ),
            array(
                array( "itemid" =>     0, "droprate" => 994),
                array( "itemid" => 17829, "droprate" => 1), 
                array( "itemid" => 17945, "droprate" => 1), 
                array( "itemid" => 17467, "droprate" => 1), 
                array( "itemid" => 13690, "droprate" => 1),
                array( "itemid" => 13109, "droprate" => 2),
            ),
        );
        $bcnms_master_table['the_hills_are_alive'] = array(
            array( 
                array( "itemid" =>  4135, "droprate" =>  295), 
                array( "itemid" =>  4119, "droprate" =>  250), 
                array( "itemid" =>  4173, "droprate" =>  196), 
                array( "itemid" =>  4175, "droprate" =>  214), 
            ),
            array( 
                array( "itemid" => 18047, "droprate" =>  188),
                array( "itemid" => 17939, "droprate" =>   27),
                array( "itemid" => 17937, "droprate" =>  170),
                array( "itemid" =>  1441, "droprate" =>  295),
                array( "itemid" => 18351, "droprate" =>   27),
                array( "itemid" => 17464, "droprate" =>   71),
                array( "itemid" => 17575, "droprate" =>  196),
            ),
            array( 
                array( "itemid" => 18211, "droprate" =>   45),
                array( "itemid" => 17576, "droprate" =>  259),
                array( "itemid" => 17245, "droprate" =>  241),
                array( "itemid" => 17838, "droprate" =>  143),
                array( "itemid" =>  1442, "droprate" =>  161),
                array( "itemid" => 17996, "droprate" =>  143),
                array( "itemid" => 17578, "droprate" =>   36),
            ),
            array( 
                array( "itemid" =>   683, "droprate" =>  446),
                array( "itemid" =>   908, "droprate" =>  420),
                array( "itemid" =>  1312, "droprate" =>   71),
                
            ),
            array( 
                array( "itemid" =>   887, "droprate" =>  116),
                array( "itemid" =>   645, "droprate" =>   89),
                array( "itemid" =>   902, "droprate" =>   71),
                array( "itemid" =>   702, "droprate" =>  152),
                array( "itemid" =>   737, "droprate" =>  107),
                array( "itemid" =>   823, "droprate" =>   89),
                array( "itemid" =>  1465, "droprate" =>   45),
                array( "itemid" =>  4173, "droprate" =>   71),
                array( "itemid" =>   700, "droprate" =>  107),
                array( "itemid" =>   703, "droprate" =>  223),
                array( "itemid" =>   738, "droprate" =>  116),
                array( "itemid" =>   830, "droprate" =>   54),
                array( "itemid" =>   895, "droprate" =>   54),
                array( "itemid" =>  1132, "droprate" =>   71),
                array( "itemid" =>  4172, "droprate" =>   45),
                array( "itemid" =>   866, "droprate" =>   54),
                array( "itemid" =>  4174, "droprate" =>   63),
                array( "itemid" =>  4175, "droprate" =>   45),
            ),
            array( 
                array( "itemid" =>   683, "droprate" =>  268),
                array( "itemid" =>  1525, "droprate" =>  121),
                array( "itemid" =>  4205, "droprate" =>   80),
                array( "itemid" =>  4201, "droprate" =>  143),
                array( "itemid" =>  4199, "droprate" =>  214),
                array( "itemid" =>  4203, "droprate" =>  196),
            ),
            array( 
                array( "itemid" =>   646, "droprate" =>  107),
                array( "itemid" =>  4211, "droprate" =>   89),
                array( "itemid" =>   645, "droprate" =>  179),
                array( "itemid" =>  4213, "droprate" =>  134),
                array( "itemid" =>  4207, "droprate" =>  152),
                array( "itemid" =>  4209, "droprate" =>   80),
                array( "itemid" =>   739, "droprate" =>   80),
                array( "itemid" =>   738, "droprate" =>  107),
                array( "itemid" => 17698, "droprate" =>  152),
            ),
            array( 
                array( "itemid" =>  3343, "droprate" => 1000),
            ),
            array( 
                array( "itemid" =>   887, "droprate" =>  139),
                array( "itemid" =>   645, "droprate" =>   59),
                array( "itemid" =>   902, "droprate" =>   50),
                array( "itemid" =>   702, "droprate" =>  109),
                array( "itemid" =>   737, "droprate" =>   69),
                array( "itemid" =>  1465, "droprate" =>   99),
                array( "itemid" =>  4173, "droprate" =>   79),
                array( "itemid" =>   700, "droprate" =>  129),
                array( "itemid" =>   644, "droprate" =>  119),
                array( "itemid" =>   844, "droprate" =>   69),
                array( "itemid" =>   703, "droprate" =>  168),
                array( "itemid" =>   738, "droprate" =>  129),
                array( "itemid" =>   895, "droprate" =>  109),
                array( "itemid" =>  1132, "droprate" =>   79),
                array( "itemid" =>  4174, "droprate" =>   69),
                array( "itemid" =>   866, "droprate" =>   79),
                array( "itemid" =>  4172, "droprate" =>   50),
                array( "itemid" =>   823, "droprate" =>   89),
            ),
            array( 
                array( "itemid" =>  1110, "droprate" =>  109),
                array( "itemid" =>   836, "droprate" =>   89),
                array( "itemid" =>   658, "droprate" =>   79),
                array( "itemid" =>   837, "droprate" =>   99),
                array( "itemid" =>   942, "droprate" =>  188),
                array( "itemid" =>   844, "droprate" =>  238),
                array( "itemid" =>  1132, "droprate" =>  109),
            ),
            array( 
                array( "itemid" =>   722, "droprate" =>   79),
                array( "itemid" =>  1446, "droprate" =>  257),
                array( "itemid" =>   703, "droprate" =>  337),
                array( "itemid" =>   831, "droprate" =>  149),
            ),
        );
    // ENM
        $bcnms_master_table['shell_we_dance'] = array(
            array(
                array("itemid" =>    0, "droprate" =>  34), 
                array("itemid" => 1762, "droprate" => 375), 
                array("itemid" => 1767, "droprate" => 328), 
                array("itemid" => 1771, "droprate" => 263), 
            ),
            array(
                array("itemid" =>    0, "droprate" =>  812),
                array("itemid" => 1842, "droprate" => 188), 
            ),
            array(
                array("itemid" =>     0, "droprate" =>  199),
                array("itemid" => 18099, "droprate" => 150), 
                array("itemid" => 17365, "droprate" => 175), 
                array("itemid" => 18015, "droprate" => 238), 
                array("itemid" => 4990, "droprate" => 238), 
            ),
            array(
                array("itemid" =>     0, "droprate" =>  199),
                array("itemid" => 18099, "droprate" => 150), 
                array("itemid" => 17365, "droprate" => 175), 
                array("itemid" => 18015, "droprate" => 238), 
                array("itemid" => 4990, "droprate" => 238), 
            ),
        );
        $bcnms_master_table['brothers'] = array(
            array(
                array("itemid" =>     0, "droprate" =>   59),
                array("itemid" =>  1767, "droprate" =>  271),
                array("itemid" =>  1762, "droprate" =>  340),
                array("itemid" =>  1771, "droprate" =>  330),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  956),
                array("itemid" =>  1842, "droprate" =>   44),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  118),
                array("itemid" => 15302, "droprate" =>  123),
                array("itemid" => 17277, "droprate" =>  163),
                array("itemid" => 17707, "droprate" =>  167),
                array("itemid" => 18098, "droprate" =>  148),
                array("itemid" =>  4748, "droprate" =>  281),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  118),
                array("itemid" => 15302, "droprate" =>  128),
                array("itemid" => 17277, "droprate" =>  163),
                array("itemid" => 17707, "droprate" =>  167),
                array("itemid" => 18098, "droprate" =>  153),
                array("itemid" =>  4748, "droprate" =>  271),
            ),
        );
        $bcnms_master_table['holy_cow'] = array(
            array(
                array("itemid" =>  1771, "droprate" =>  200),
                array("itemid" =>  1767, "droprate" =>  400),
                array("itemid" =>  1762, "droprate" =>  400),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  950),
                array("itemid" =>  1842, "droprate" =>   50),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  275),
                array("itemid" => 17209, "droprate" =>  125),
                array("itemid" => 18356, "droprate" =>  125),
                array("itemid" => 13648, "droprate" =>  175),
                array("itemid" => 13694, "droprate" =>  125),
                array("itemid" =>  4748, "droprate" =>  175),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  275),
                array("itemid" => 17209, "droprate" =>  125),
                array("itemid" => 18356, "droprate" =>  125),
                array("itemid" => 13648, "droprate" =>  175),
                array("itemid" => 13694, "droprate" =>  125),
                array("itemid" =>  4748, "droprate" =>  175),
            ),
        );
        $bcnms_master_table['pulling_the_plug'] = array(
            array(
                array("itemid" =>  5287, "droprate" =>   97),
                array("itemid" =>  5286, "droprate" =>  174),
                array("itemid" =>  5288, "droprate" =>  124),
                array("itemid" =>  5293, "droprate" =>  140),
                array("itemid" =>  5289, "droprate" =>  124),
                array("itemid" =>  5292, "droprate" =>  124),
                array("itemid" =>  5291, "droprate" =>   93),
                array("itemid" =>  5290, "droprate" =>  124),
            ),
            array(
                array("itemid" =>  1794, "droprate" =>  291),
                array("itemid" =>  1795, "droprate" =>  372),
                array("itemid" =>  1795, "droprate" =>  337),
            ),
            array(
                array("itemid" =>  1796, "droprate" =>  523),
                array("itemid" =>  1797, "droprate" =>  477),
            ),
            array(
                array("itemid" =>     0, "droprate" =>  736),
                array("itemid" =>  1790, "droprate" =>  167),
                array("itemid" =>  1792, "droprate" =>   66),
                array("itemid" =>  1791, "droprate" =>   31),
            ),
        );